### ISSUE TITLE
viper.Watch() support

### ISSUE THREAD

**Issue by abh** [num30/config#14]
First: this is great; I'm glad I found it!

Every few years I do another attempt at using Viper and always end up finding it too miserable to make its structure support work reasonably well enough. I'm glad to have found your code where you went through all the hassle.

A feature request: It'd be great to have support for viper's configuration reloading feature ("viper.Watch()").

**Comment by DenisPalnitsky** [comment]
Thanks, I'm glad you found it useful!
 I implemented Watch in #15  for config files only. It's a bit more complex with environment variables mainly because it goes against the env vars design. However, If that is a demand for that then I don't see the reason for not implementing it.

**Comment by DenisPalnitsky** [comment]
fixed by #15
